services:
  ecg-rec:
    build: .
    container_name: model
    restart: no

    dns:
      - 8.8.8.8
      - 1.1.1.1

    volumes:
      - ./data:/app/data
      - ./dist:/app/dist
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./logs:/app/logs
      - ./.env:/app/.env

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
